#####################################################################
#                                                                   #    
# THIS FILE IS NO LONGER USED, SPLIT INTO MULTIPLE YAML FILES, SEE: #
#                        /automations/ FOLDER                       #
#                                                                   #
#####################################################################
