
- alias: 'Set house to bedtime/nightime'
  trigger:
    - platform: time
      at: '21:30:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bedtime
    - service: input_select.select_option
      data:
        entity_id: input_select.living_room_light_mode
        option: auto

- alias: 'Set house out of bedtime/nightime'
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.bedtime

- alias: 'Adjust living room lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.living_room_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.living_room
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_light_rooms.state|int}}
        entity_id:
          - light.living_room

- alias: 'Adjust front room lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.front_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.front_room
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.front_room

- alias: 'Adjust downstairs hallway lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.downstairs_hallway_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.downstairs_hallway
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.downstairs_hallway


####################################################
#    NOTE THAT THIS IS SPECIAL, ONLY CHECKING A    #
#              SPECIFIC LIGHT (SPOT_5)             #
####################################################

# This is because the downstairs motion sensor is triggering the first three lights

- alias: 'Adjust hallway lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.hallway_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.hallway_spot_5
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.hallway_lights

- alias: 'Adjust kitchen lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.kitchen_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.kitchen
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_light_rooms.state|int}}
        entity_id:
          - light.kitchen

- alias: 'Adjust bedroom lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.bedroom_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.bedroom
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_light_rooms.state|int}}
        entity_id:
          - light.bedroom

- alias: 'Adjust Sophies bedroom lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.sophies_bedroom_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.sophies_bedroom
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.sophies_bedroom

####################################################
#    NOTE THAT THIS IS SPECIAL, ONLY CHECKING A    #
#              SPECIFIC LIGHT (SPOT_5)             #
####################################################

- alias: 'Adjust Den lights brightness'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.den_light_mode
        state: 'auto'
      - condition: state
        entity_id: light.main_office_light
        state: 'on'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_light_rooms.state|int}}
        entity_id:
          - light.main_office_light

