##### LIVING ROOM #####

- alias: 'Living room lights presence on'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.living_room
          state: 'off'
        - condition: state
          entity_id: input_select.living_room_light_mode
          state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.living_room

- alias: 'Livingroom lights presence off'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.living_room_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.living_room_motion
                state: 'off'
                for:
                  minutes: 20
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.living_room_motion
                state: 'off'
                for:
                  minutes: 4
              - condition: template
                value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.living_room.last_changed)) <= 360 }}"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.living_room

- alias: 'Livingroom lights off at night'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.living_room_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.living_room

##### FRONT ROOM #####

- alias: 'Front room lights presence on'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_room_motion
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.front_room
          state: 'off'
        - condition: state
          entity_id: input_select.front_room_light_mode
          state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.front_room

- alias: 'frontroom lights presence off'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_room_motion
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: binary_sensor.front_room_motion
      to: 'off'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.front_room_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.front_room_motion
                state: 'off'
                for:
                  minutes: 20
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.front_room_motion
                state: 'off'
                for:
                  minutes: 4
              - condition: template
                value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.front_room.last_changed)) <= 360 }}"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.front_room

- alias: 'frontroom lights off at night'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_room_motion
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.front_room_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.front_room

##### Downstairs hallway #####

- alias: 'Downstairs hallway lights presence on'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.downstairs_hallway
          state: 'off'
        - condition: state
          entity_id: input_select.downstairs_hallway_light_mode
          state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.downstairs_hallway

- alias: 'downstairs hallway lights presence off'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      to: 'off'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.downstairs_hallway_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.downstairs_hallway_motion
                state: 'off'
                for:
                  minutes: 20
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.downstairs_hallway_motion
                state: 'off'
                for:
                  minutes: 2
              - condition: template
                value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.downstairs_hallway.last_changed)) <= 300 }}"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.downstairs_hallway

- alias: 'downstairs hallway lights off at night'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.downstairs_hallway_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.downstairs_hallway

##### HALLWAY #####

- alias: 'Hallway lights presence on'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.hallway_spot_5
          state: 'off'
        - condition: state
          entity_id: input_select.hallway_light_mode
          state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int}}
        entity_id:
          - light.hallway_lights

# Automation motion downstairs hallway
- alias: "Hallway first lights presence downstairs"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.hallway_light_mode
        state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int }}
        entity_id: 
          - light.hallway_spot_1
    - delay:
        milliseconds: 500    
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int }}
        entity_id: 
          - light.hallway_spot_2        
    - delay:
        milliseconds: 500
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_dark_rooms.state|int }}
        entity_id: 
          - light.hallway_spot_4

- alias: 'Hallway lights presence off'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.hallway_light_mode
        state: 'auto'
      - condition: state
        entity_id: binary_sensor.hallway_motion
        state: 'off'
        for:
          seconds: 30
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hallway_lights

# Automation motion hallway off from downstairs
- alias: "Hallway first lights off from downstairs"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.downstairs_hallway_motion
      from: 'on'
      to: 'off'
      for: '00:00:10'
  condition:
      condition: and
      conditions:
        - condition: state
          state: 'on'
          entity_id: light.hallway_lights
        - condition: template
          value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.hallway_lights_presence_on.attributes.last_triggered) | int > 30 }}'
  action:
    - service: light.turn_off
      entity_id:
        - light.hallway_spot_1
        - light.hallway_spot_2
        - light.hallway_spot_4

##### KITCHEN #####

- alias: 'kitchen lights presence on'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        - condition: state
          entity_id: input_select.kitchen_light_mode
          state: 'auto'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >
          {{ states.sensor.target_brightness_light_rooms.state|int}}
        entity_id:
          - light.kitchen

- alias: 'kitchen lights presence off'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for:
        minutes: 20
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for:
        minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.kitchen_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'off'
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.kitchen_motion
                state: 'off'
                for:
                  minutes: 20
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.kitchen_motion
                state: 'off'
                for:
                  minutes: 2
              - condition: template
                value_template: "{{ (as_timestamp(now())-as_timestamp(states.light.kitchen.last_changed)) <= 300 }}"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen

- alias: 'kitchen lights off at night'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.kitchen_light_mode
        state: 'auto'
      - condition: state
        entity_id: input_boolean.bedtime
        state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.kitchen
